Dockerfile, README.rst
=> Created Dockerfile

django_x509/base/models.py, django_x509/tests/test_ca.py, django_x509/tests/test_cert.py
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/4952599658758144/t
=> Error: [('PEM Routines','PEM_READ_BIO','no start line')] #12

django_x509/base/models.py, django_x509/tests/test_ca.py, django_x509/tests/test_cert.py, requirements-test.txt, requirements.txt
Simplified the solution to #14
=> Simplified the solution to #14

django_x509/admin.py, django_x509/base/admin.py, django_x509/static/django-x509/js/switcher.js
=> [UX] New vs Import javascript switcher #10

django_x509/base/admin.py, django_x509/static/django-x509/js/x509-admin.js
Task: https://codein.withgoogle.com/dashboard/task-instances/6534612266254336/
=> Automatically select certificate and private_key on click #25

.travis.yml
=> [ci] Add pending migration check

django_x509/tests/test_cert.py
=> Added a test to make sure error is raised for serial number clashes.

django_x509/base/models.py, django_x509/tests/test_ca.py, django_x509/tests/test_cert.py
Messages will be more human readable.
The square brackets are removed and line breaks are added.
Fixes #44
=> [models] Improve error message format #44

.travis.yml, requirements-test.txt, runcheckmigration
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5542554570326016/
=> [ci] add ci check for migrations

.travis.yml
=> [qa] Added commit message style check  #50

requirements.txt
Update dependencies in requirements.txt file.
=> [requirements] cryptography>=2.4.0,<2.5.0

.gitignore, django_x509/tests/test_ca.py, django_x509/tests/test_cert.py, requirements.txt
Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>
=> Bumped cryptography version to 2.6.1

.travis.yml, requirements.txt
Supports:
Python 2.7 / Django 1.11
Python 3.5 / Django 2.0 - 2.2
Python 3.6 / Django 2.0 - 2.2
Python 3.7 / Django 2.0 - 2.2
=> [django-x509] Update to Django 2.2 et al

requirements.txt
Testing the build before issuing a new release for this package.
=> [requirements] cryptography>=2.4.0,<2.9.0

.travis.yml, requirements-test.txt, runcheckmigration, runisort
Change .travis.yml to run common CI test using new common checks script in openwisp-utils. Also remove unnecessary script and update openwisp-utils.
=> [ci] Migrate to common CI script

.travis.yml
=> [Travis] Fix Warnings

CHANGES.rst, django_x509/__init__.py, requirements.txt
=> 0.6.1 release

requirements.txt
=> [deps] cryptography 2.9 #88

CHANGES.rst, django_x509/__init__.py
Version 0.7.0 [2020-05-16]
--------------------------
- Added feature to renew certificates
- Updated dependency to support cryptography 2.9
=> 0.7.0 release

CHANGES.rst, tests/openwisp2/settings.py
=> [docs] Mention how to upgrade to swappable #94

.travis.yml, requirements-test.txt, requirements.txt, setup.cfg, tests/openwisp2/settings.py
Updated dependencies, django 3.1, cryptography 3.0.
=> [deps] Updated dependencies, django 3.1, cryptography 3.0

requirements.txt
Updated cryptography to latest(3.1.1)
closes #103
=> [dpes] Upgraded dependency

CHANGES.rst, django_x509/__init__.py, django_x509/base/admin.py, requirements-test.txt, requirements.txt
=> 0.9.1 release

django_x509/base/admin.py, django_x509/base/mixin.py, django_x509/tests/test_ca.py
=> [mixin] Moved download `crl-view` to mixin #116

.github/workflows/ci.yml, django_x509/apps.py, django_x509/base/admin.py, django_x509/base/models.py, requirements.txt, tests/openwisp2/urls.py
Added django version 3.2 and 4.0a1
, removed 2.2.0, updated some changes
that were required.
Fixes #122
=> [deps] Added support for Django 3.2 and Django 4.0a #122 

django_x509/base/admin.py
Added validity_end to admin list of Ca and Cert.
=> [feature] Added validity_end to admin list of Ca and Cert

.github/workflows/ci.yml, README.rst, django_x509/__init__.py, requirements.txt, tests/openwisp2/__init__.py, tests/openwisp2/sample_x509/apps.py
- Dropped support for Python 3.7
- Bumped cryptography~=41.0.1
=> [deps] Added support for Django 4.1.0 and 4.2.0

django_x509/__init__.py
Fixed non-compliant get_version() output.
=> [fix] Fixed non-compliant get_version() output

.github/workflows/ci.yml, django_x509/base/admin.py, django_x509/tests/test_admin.py
=> [fix] Admin actions require model permissions

.github/workflows/pypi.yml, requirements-test.txt, requirements.txt, setup.py
Added workflow for publishing to PyPI
=> [ci] Added workflow for publishing to PyPI

.github/workflows/version-branch.yml, CHANGES.rst, django_x509/__init__.py, requirements-test.txt, requirements.txt
=> [ci] Added GitHub workflow to replicate commits to version branch

.github/workflows/ci.yml, README.rst, requirements.txt
=> [deps] Added support for Python >3.10,<3.14 and Django 5.2 #175 

.github/workflows/ci.yml
Updated Django 5.2rc0 to 5.2.0.
=> [ci] Updated Django 5.2rc0 to 5.2.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/workflows/ci.yml, .github/workflows/pypi.yml
=> [qa] Reformatted YAML and Markdown files
